# Generated by Django 4.0.6 on 2022-08-02 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.IntegerField(default=0),
        ),
    ]
