# Generated by Django 4.0.6 on 2022-07-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='like_account',
            new_name='like_count',
        ),
    ]
