# Generated by Django 4.0.6 on 2022-07-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AlterField(
            model_name='feed',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
