# Generated by Django 4.0.6 on 2022-07-23 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_rename_content_id_bookmark_feed_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
