# Generated by Django 4.0.6 on 2022-07-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_feed_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='feed_id',
            field=models.IntegerField(default=0),
        ),
    ]
